server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-ribbon
eureka:
  host: discovery
  client:
    serviceUrl:
      defaultZone: http://root@password${eureka.host}:8761/eureka/
  instance:
    preferIpAddress: true