spring:
  profiles:
    active: dev-peer3
#      将peer1自己注册到peer2这个Eureka上面去
#      将peer2自己注册到peer1这个Eureka上面去
#如果注册中心是高可用的，那么各个微服务配置只需要将defaultZone 改为如下即可：
# eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka