
server:
  port: 8763
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://http://root@passwordpeer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/

