server:
  port: 8000
  servlet-path: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true
#    hostname : discovery   # 指定主机名时候通过主机名访问,否则通过ip地址
spring:
  application:
    name: microservice-provider-user    # 项目名称尽量用小写
  datasource:                           # 指定数据源
    platform: mysql                # 指定数据源类型
    schema: classpath:schema.sql        # 指定数据库的建表脚本
    data: classpath:data.sql            # 指定数据库的insert脚本

    # 数据库参数  #如果有配置,按照这个配置优先,如果没有按照db.properties配置

dev:
  spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/cloud?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123
      driverClassName: com.mysql.jdbc.Driver
       # 参数
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR



