
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://root:password@peer1:8761/eureka/,http://root:password@peer2:8762/eureka/,http://root:password@peer3:8763/eureka/

